# Generated by Django 5.2.8 on 2026-01-03 18:26

import mainapp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=mainapp.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=mainapp.fields.EncryptedTextField(),
        ),
    ]
