# Generated by Django 5.2.8 on 2025-12-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='token_added_at',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
