# Generated by Django 5.2.8 on 2025-12-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_spotifytoken_token_added_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='expires_at',
        ),
    ]
