# Generated by Django 5.2.8 on 2025-12-29 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_spotifytoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 29, 19, 36, 56, 505320, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
