# Generated by Django 5.2.8 on 2025-12-29 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_spotifytoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
